version: "3"
services:
  vue:
    container_name: vue_container
    build: ./docker/vue
    ports:
      - 8080:8080
    volumes:
      - ./vue:/vue
    stdin_open: true
    tty: true
    environment:
      TZ: Asia/Tokyo
    networks:
      - default
    command: yarn start

  server:
    container_name: express_container
    build: ./docker/express
    ports:
      - 3000:3000
    volumes:
      - ./express:/express
    tty: true
    environment:
      CHOKIDAR_USEPOLLING: 1
      TZ: Asia/Tokyo
    command: yarn nodemon
    networks:
      - default
    depends_on:
      - db

  db:
    container_name: mysql_container
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./mysql/conf/my.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./mysql/init_db:/docker-entrypoint-initdb.d
      - vue_express_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ="Asia/Tokyo"
    networks:
      - default

networks:
  default:

volumes:
  vue_express_data:
